language: node_js
node_js:
  - "node"

install:
  - npm install
  - npm install htmllint-cli

script:
  - npm test
  - htmllint **/*.html 2>&1 | tee output.log
  - grep -q '^\[htmllint error' output.log && exit 1 || true
